#!/usr/bin/env python

from pprint import pprint
from dbus import SystemBus, Interface, Dictionary

settings_name = 'org.freedesktop.NetworkManagerUserSettings'
settings_path = '/org/freedesktop/NetworkManagerSettings'
manager_name = 'org.freedesktop.NetworkManager'
manager_path = '/org/freedesktop/NetworkManager'
manager_interface = 'org.freedesktop.NetworkManager'
settings_interface = 'org.freedesktop.NetworkManagerSettings'
connection_interface = 'org.freedesktop.NetworkManagerSettings.Connection'
property_interface = 'org.freedesktop.DBus.Properties'

def format_settings(settings, indent):
    return '\n'.join(format_setting(key, value, indent)
                     for key, value in settings.items())

def format_setting(key, value, indent):
    pieces = [indent, key, ': ']
    if isinstance(value, dict):
        pieces.append('\n')
        pieces.extend(format_settings(value, indent + '  '))
    elif isinstance(value, list):
        if value.signature == 's':
            pieces.append(', '.join(value))
        elif value.signature == 'y':
            pieces.append(''.join(map(chr, value)))
        else:
            if not value:
                pieces.append('empty ')
            pieces.append('array of %s/%d'
                          % (value.signature, value.variant_level))
            if value:
                pieces.append(': ')
            pieces.append(', '.join(map(str, value)))
    else:
        pieces.append(str(value))
    return ''.join(pieces)
    
def pprint_settings(settings, indent='  '):
    print format_settings(settings, indent)
    
def main():
    bus = SystemBus()
    settings_proxy = bus.get_object(settings_name, settings_path)
    settings = Interface(settings_proxy, settings_interface)

    # Get the VPN connection.
    for connection_path in settings.ListConnections():
        connection_proxy = bus.get_object(settings_name, connection_path)
        connection = Interface(connection_proxy, connection_interface)
        settings = connection.GetSettings()

        print connection_path
        pprint_settings(settings)

if __name__ == '__main__':
    main()
