#!/usr/bin/env python

from pprint import pprint
from dbus import SystemBus, Interface, Dictionary

settings_name = 'org.freedesktop.NetworkManagerUserSettings'
settings_path = '/org/freedesktop/NetworkManagerSettings'
manager_name = 'org.freedesktop.NetworkManager'
manager_path = '/org/freedesktop/NetworkManager'
manager_interface = 'org.freedesktop.NetworkManager'
settings_interface = 'org.freedesktop.NetworkManagerSettings'
connection_interface = 'org.freedesktop.NetworkManagerSettings.Connection'
property_interface = 'org.freedesktop.DBus.Properties'

def pprint_settings(settings, indent='  '):
    for key, value in settings.items():
        print indent + key + ':',
        if isinstance(value, dict):
            print
            pprint_settings(value, indent + '  ')
        elif isinstance(value, list):
            if value.signature == 's':
                print ', '.join(value)
            elif value.signature == 'y':
                print ''.join(map(chr, value))
            else:
                if not value:
                    print 'empty',
                print 'array of',
                print '%s/%d' % (value.signature, value.variant_level),
                if value:
                    print ':',
                print ', '.join(value)
        else:
            print value
    
def main():
    bus = SystemBus()
    settings_proxy = bus.get_object(settings_name, settings_path)
    settings = Interface(settings_proxy, settings_interface)

    # Get the VPN connection.
    for connection_path in settings.ListConnections():
        connection_proxy = bus.get_object(settings_name, connection_path)
        connection = Interface(connection_proxy, connection_interface)
        settings = connection.GetSettings()

        print connection_path
        pprint_settings(settings)

if __name__ == '__main__':
    main()
